### ISSUE TITLE
Got 2 errors when register

### ISSUE THREAD

**Issue by Mitchou** [evilsocket/openbank#11]
Hi,

Got 2 errors when I register a new user on a fresh install of Openbank
- QueryException in Connection.php line 713: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null (SQL: insert into `user_settings` (`user_id`, `name`, `value`, `updated_at`, `created_at`) values (3, blockonomics_api_key, , 2016-06-25 19:52:48, 2016-06-25 19:52:48))
- PDOException in Connection.php line 441: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null

Maybe because I use MariaDB instead of MySQL...

I can sucessfull login after this erros but I can't go to settings
- BadMethodCallException in Builder.php line 2345: Call to undefined method Illuminate\Database\Query\Builder::getDefault()
- ErrorException in Builder.php line 2345: Call to undefined method Illuminate\Database\Query\Builder::getDefault() (View: /var/www/html/openbank/resources/views/settings.blade.php)

Just to be sure, I put all my opendirectory to www-data owner

Here my system:
Rpi B with Rasbian Lite up-to-date
Nginx 1.6.2, Php56
Database on external server: MariaDB 10.0.23

Thx for your work. Openbank is really a good idea !! :)

**Comment by blackout314** [comment]
me too same problem.. 
a cosa serve sta API? la si puo sostituire con una pubblica?

**Comment by blackout314** [comment]
error is fixed with my merge request - puoi chiudere sta issue
