### ISSUE TITLE
Request: Adjustable timespan for price graph

### ISSUE THREAD

**Issue by xqus** [evilsocket/openbank#4]
Currenty the price graph goes back one hour. It would be nice if this were adjustable.

**Comment by evilsocket** [comment]
i'll work on it ;)

**Comment by xqus** [comment]
Seems like there is some bugs.
1 month and week shows up all white.
The graphs shows different proces, for same time. Eg. the 24 hour graph shows USD 668 at a time, while the one hour graph shows over UDS 700 for the same time.

**Comment by evilsocket** [comment]
you see white charts because you don't have enough data, u need your cronjob to collect 1 week of data (for instance) to see the 1 week panel ...
